# Image directory (default: images)
image_dir: images


# General
logo: images/demo/logo.jpg # logo (35px)
cover:
favicon:
rss:

# Author
author:
    gravatar: gravatar@gmail.com
    picture:
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'
    locate: France
    github: https://github.com/
    stack_overflow: http://stackoverflow.com/users/
    linked_in: https://linkedin.com/
    twitter: https://twitter.com/
    facebook: https://facebook.com/
    google_plus: https://plus.google.com/

# Post thumbnail image (disable: 0, enable: 1)
thumbnail_image: 0

# Miscellaneous
google_analytics:
