# General
general:
    # logo (35px)
    logo: images/demo/logo.jpg

# Personal profile
author:
    gravatar: gravatar@gmail.com
    figure:
    cover:
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'
    locate: France
    github: https://github.com/
    linkedin: https://linkedin.com/
    twitter: https://twitter.com/
    facebook: https://facebook.com/
    googleplus: https://plus.google.com/

config:
    rss: